### ISSUE TITLE
这个可以获取对象的名称和id吗？

### ISSUE THREAD

**Issue by landonzeng** [jiadevr/GetBPParams#1]
你好，我也是第一次接触UE，刚好有个需求，就是需要获取导出对象的名称和Id，用来做BIM的模型映射

**Comment by landonzeng** [comment]
还有我要怎么使用，能提供一个简单的教程吗？

**Comment by jiadevr** [comment]
这个分享的目的是解决**某一**蓝图类成员变量的批量导出/更改，具体使用可以看我在readme中的b站文章。对于BIM模型在场景里主要以多个StaticMesh的形式存在，你的需求使用[Editor Utilities](https://dev.epicgames.com/documentation/zh-cn/unreal-engine/scripted-actions-in-unreal-engine?application_version=5.5)更合适哦

**Comment by landonzeng** [comment]
好的，感谢回答
